"""Model invocation utilities for the discovery pipeline."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Dict, Mapping, MutableMapping, Optional


ModelInvoker = Callable[[str, str], str]


@dataclass
class AdapterConfig:
    name: str
    description: str
    models: Mapping[str, ModelInvoker]


class ModelRegistry:
    """Registry for model adapter collections (stub/local/remote)."""

    def __init__(self) -> None:
        self._adapters: MutableMapping[str, AdapterConfig] = {}

    def register(self, key: str, config: AdapterConfig) -> None:
        self._adapters[key] = config

    def get(self, key: str) -> AdapterConfig:
        if key not in self._adapters:
            raise KeyError(f"Unknown adapter '{key}'. Available: {sorted(self._adapters)}")
        return self._adapters[key]

    def default(self) -> AdapterConfig:
        return self._adapters.get("stub", next(iter(self._adapters.values())))

    def choices(self) -> Mapping[str, AdapterConfig]:
        return dict(self._adapters)


def build_default_registry() -> ModelRegistry:
    registry = ModelRegistry()

    def _stub_invoker(model: str, prompt: str) -> str:
        _ = (model, prompt)
        import json

        return json.dumps(
            {
                "summary": "Stub summary generated by stub adapter",
                "entities": [],
                "responsibilities": [],
                "dependencies": [],
                "confidence": 0.5,
            }
        )

    registry.register(
        "stub",
        AdapterConfig(
            name="stub",
            description="Deterministic stubbed responses (offline/default)",
            models={
                "local://python-mini": _stub_invoker,
                "cloud://gpt-standard": _stub_invoker,
                "cloud://gpt-advanced": _stub_invoker,
            },
        ),
    )

    def _echo_invoker(model: str, prompt: str) -> str:
        import json

        return json.dumps(
            {
                "summary": "Echo model response",
                "entities": [],
                "responsibilities": [],
                "dependencies": [],
                "confidence": 0.5,
                "debug_prompt": prompt,
            }
        )

    registry.register(
        "echo",
        AdapterConfig(
            name="echo",
            description="Local echo adapter useful for debugging prompts",
            models={
                "local://python-mini": _echo_invoker,
                "cloud://gpt-standard": _echo_invoker,
                "cloud://gpt-advanced": _echo_invoker,
            },
        ),
    )

    return registry


__all__ = [
    "ModelInvoker",
    "AdapterConfig",
    "ModelRegistry",
    "build_default_registry",
]
